### ISSUE TITLE
Name generator missing

### ISSUE THREAD

**Issue by wiploo** [ironarachne/ironarachne#9]
Hi @BenOvermyer, thanks for you great work!

I'm used to generate npc name using your fancy script at https://muna.ironarachne.com/ but it's a few weeks that it doesn't work anymore.

I have searched on the main website but I can't find this great script?

Is it available or abbandoned? If it is abbandoned, can you perhaps share the script?

Many thanks!

**Comment by BenOvermyer** [comment]
@wiploo That name generator API moved and is now available here: https://names.ironarachne.com/. The format of requests changed also, so please review the response at the root `/` for instructions on how to use it.

Also, the source code for that API is available here: https://github.com/ironarachne/muna
